# Crea la estructura

news_sites:
  elcolombiano:
    url: http://elcolombiano.com
    queries:
        homepage_article_links: '.noticia-segundaria a'
  futbolred:  
    url: http://futbolred.com
    queries:
        homepage_article_links: '.cintillo-multimedia a'
  
